spring:
  # thymelaef模板
  thymeleaf:
    # 缓存机制
    cache: false
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.220.29.69:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: seckill
    password: wtr4w87DD8ZCfCPT
    hikari:
      # 链接池名
      pool-name: DateHikariCP
      # 最少链接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 最大链接数
      maximum-pool-size: 10
      # 从链接返回的链接自动提交
      auto-commit: true
      # 链接最大存活时间 0为永久
      max-lifetime: 180000
      # 链接超时时间，默认30秒
      connection-timeout: 30000
      # 链接测试是否可用的查询语句
      connection-test-query: SELECT 1
  # Spring Boot 2.6及 更高版本使用的是PathPatternMatcher，而Springfox使用的路径匹配是基于AntPathMatcher的，所以需要配置。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis
  redis:
    host: 124.220.29.69
    port: 6379
    database: 0
    # 超时重连时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大链接数
        max-active: 8
        # 最大连接阻塞时间
        max-wait: 10000ms
        # 最大空闲链接
        max-idle: 200
        # 最小空闲链接
        min-idle: 5

server:
  port: 14008

mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认为类的别名）
  type-aliases-package: com.yzp.pojo

# mybatis sql方法打印（方法接口所在的包，不是mapper，xml所在的包）
logging:
  level:
    com.yzp.mapper: debug